DROP VIEW IF EXISTS v_ranking;
DROP VIEW IF EXISTS v_tournament_standings;
DROP VIEW IF EXISTS v_player_stats;

DROP TABLE IF EXISTS club_president_history;
DROP TABLE IF EXISTS club_membership_history;
DROP TABLE IF EXISTS rating_history;
DROP TABLE IF EXISTS arbiter_class_history;
DROP TABLE IF EXISTS player_class_history;
DROP TABLE IF EXISTS penalty;
DROP TABLE IF EXISTS penalty_role_context;
DROP TABLE IF EXISTS norm;
DROP TABLE IF EXISTS title_history;
DROP TABLE IF EXISTS round_rating;
DROP TABLE IF EXISTS tournament_player;
DROP TABLE IF EXISTS tournament_arbiter;
DROP TABLE IF EXISTS game_over;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS game_over_reason;
DROP TABLE IF EXISTS round;
DROP TABLE IF EXISTS tournament;
DROP TABLE IF EXISTS club CASCADE;
DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS tournament_system;
DROP TABLE IF EXISTS tempo;
DROP TABLE IF EXISTS title;
DROP TABLE IF EXISTS arbiter_class;
DROP TABLE IF EXISTS player_class;

DROP FUNCTION IF EXISTS trg_fn_require_arbiter();
DROP FUNCTION IF EXISTS trg_fn_player_club_matches_history();
DROP FUNCTION IF EXISTS trg_fn_club_president_matches_history();
DROP FUNCTION IF EXISTS trg_fn_check_round_date();
DROP FUNCTION IF EXISTS trg_fn_check_round_count();
DROP FUNCTION IF EXISTS trg_fn_check_previous_rounds_finished();
DROP FUNCTION IF EXISTS trg_fn_valid_arbiter_on_game();
DROP FUNCTION IF EXISTS trg_fn_valid_penalty_context();
DROP FUNCTION IF EXISTS trg_fn_game_players_registered();
DROP FUNCTION IF EXISTS trg_fn_one_game_per_round();
DROP FUNCTION IF EXISTS trg_fn_no_round_after_close();
DROP FUNCTION IF EXISTS trg_fn_no_result_after_close();
DROP FUNCTION IF EXISTS trg_fn_no_player_after_start();
DROP FUNCTION IF EXISTS trg_fn_round_requires_start();
DROP FUNCTION IF EXISTS trg_fn_no_penalised_player();
DROP FUNCTION IF EXISTS trg_fn_no_penalised_arbiter();
DROP FUNCTION IF EXISTS trg_fn_no_penalised_main_arbiter();
DROP FUNCTION IF EXISTS trg_rating_history_update_player_rating();
DROP FUNCTION IF EXISTS trg_sync_tournament_score();
DROP FUNCTION IF EXISTS fn_close_tournament(INTEGER);
DROP FUNCTION IF EXISTS fn_player_tournament_rating(INTEGER, INTEGER);
DROP FUNCTION IF EXISTS fn_has_penalty_in_period(INTEGER, DATE, DATE);
DROP FUNCTION IF EXISTS fn_is_tournament_arbiter(INTEGER, INTEGER);
DROP FUNCTION IF EXISTS fn_tournament_rating_category(INTEGER);
DROP FUNCTION IF EXISTS _seed_tournament(TEXT, INT, INT, INT, TIMESTAMPTZ, TIMESTAMPTZ, INT, TEXT, INT, INT, INT[], INT[], INT, BOOLEAN, BOOLEAN);
